### ISSUE TITLE
Question: Source for json?

### ISSUE THREAD

**Issue by robert-chiniquy** [gbrigandi/tfschema-bindgen#12]
From the README:

> In order do (de)serialize provider's configuration, import the generated module in your application.

It seems like the schema of these structs don't exactly match the output of `terraform show json <plan file>` or ` terraform-config-inspect --json`- could you please point me at where / how you are extracting JSON from Terraform modules that does match this schema? Sorry if I'm missing something obvious.

**Comment by gbrigandi** [comment]
Hi Robert, 
The output of those commands is a state JSON file, which is an internal representation of the current infrastructure state used by Terraform to derive which changes have to be made upon applying configuration changes. For more information please refer to : https://www.terraform.io/docs/language/state/index.html
Conversely, tfschema-bindgen deals with strongly typed serialization/deserialization of terraform configuration files for a given set of previously mapped provider schemas.

**Comment by robert-chiniquy** [comment]
Thank you for the reply. I have been using it to generate files in this format (`.tf.json`). I haven't found any way to get that format out of Terraform though, I was hoping you had a method for converting `.tf` files from HCL to JSON. It seems that the provider schema, which you parse here, is all that would be needed to build an `hcldec` spec to do that.

**Comment by gbrigandi** [comment]
Unfortunately AFAIK there is no Serde support for HCL yet. Therefore, cannot parse HCL configuration files as there is no deserializer. Conversely, once deserialized, it would be possible to serialize the in-memory representation back to JSON.
As a workaround, you may want to convert the HCL formatted TF file to JSON before digesting it with tfschema-bindgen. There's a command line tool named json2hcl (https://github.com/kvz/json2hcl) that does just that. Here's an example invocation :
json2hcl -reverse < infra_hcl.tf > infra.tf.json

**Comment by robert-chiniquy** [comment]
Thank you for sharing that. Unfortunately that tool can't parse documents which contain more modern features of Terraform such as for loops like this: 
```
 usernames = [
    for i in range(5) : format("user%02d", i)
 ]
```
(which is a big syntactical change). I'm not 100% sure `hcldec' could do it either, it just seems like the only current prospect.
